-   code: h34
    description: remera
    unit_price: 4
    thumbnail: images/h/34.png
-   code: h35
    description: remera escote en v.
    unit_price: 6
    thumbnail: images/h/34.png
-   code: h36
    description: pantalon
    unit_price: 7
    thumbnail: images/h/34.png
